CREATE TABLE `catalogItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`nameHe` varchar(256) NOT NULL,
	`category` varchar(64) NOT NULL,
	`subCategory` varchar(64) NOT NULL,
	`gender` varchar(16) NOT NULL,
	`color` varchar(64) NOT NULL,
	`secondaryColor` varchar(64),
	`material` varchar(64) NOT NULL,
	`fit` varchar(32) NOT NULL,
	`pattern` varchar(32) NOT NULL,
	`styleTags` json NOT NULL,
	`occasionTags` json NOT NULL,
	`season` varchar(32) NOT NULL,
	`brand` varchar(128) NOT NULL,
	`store` varchar(128) NOT NULL,
	`priceIls` int NOT NULL,
	`budgetTier` varchar(32) NOT NULL,
	`trendRelevance` varchar(16) NOT NULL,
	`productSearchQuery` varchar(256) NOT NULL,
	`imageUrl` text,
	`upgradeReason` text NOT NULL,
	`upgradeReasonHe` text NOT NULL,
	`pairsWith` json NOT NULL,
	`upgradesFrom` json NOT NULL,
	`colorHarmonyGroups` json NOT NULL,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `catalogItems_id` PRIMARY KEY(`id`)
);
